name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-typecheck-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify environment configuration
        run: pnpm env:check

      - name: Verify privacy checklist acknowledgement
        if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
        env:
          PR_BODY: ${{ github.event.pull_request.body || '' }}
          BASE_REF: ${{ github.base_ref || '' }}
        run: |
          set -euo pipefail
          # Accept either a checked box with the phrase (flexible whitespace/case) or a direct link mention.
          if echo "$PR_BODY" | tr -d '\r' | grep -Eiq "\[[[:space:]]*[xX][[:space:]]*\].*reviewed.*completed.*checklist" || echo "$PR_BODY" | grep -qi "docs/security-privacy.md"; then
            echo "Privacy checklist acknowledged."
          else
            if [ "$BASE_REF" = "main" ]; then
              echo "::error::Please acknowledge docs/security-privacy.md in the PR description (checked box or link)."
              exit 1
            else
              echo "::warning::Privacy checklist not acknowledged. Add a checked box or link to docs/security-privacy.md."
            fi
          fi

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test
